export enum ActionTypes {
  ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST',
  ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS',
  ADD_ITEM_ERROR = 'ADD_ITEM_ERROR',
  GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST',
  GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS',
  GET_ITEMS_ERROR = 'GET_ITEMS_ERROR'
}
